require "LugliAchievements/Categories"

local M = LugliAchievements

local DEFS = {
    {
        id = "learn_level_10",
        name = "UI_LugliAch_learn_level_10_name",
        description = "UI_LugliAch_learn_level_10_desc",
        category = "autodidact",
        stat = "perk_max_level",
        target = 10,
        tier = "silver",
    },
    {
        id = "learn_perks3_10",
        name = "UI_LugliAch_learn_perks3_10_name",
        description = "UI_LugliAch_learn_perks3_10_desc",
        category = "autodidact",
        stat = "perks_at_3",
        target = 10,
        tier = "silver",
    },
    {
        id = "learn_perks5_5",
        name = "UI_LugliAch_learn_perks5_5_name",
        description = "UI_LugliAch_learn_perks5_5_desc",
        category = "autodidact",
        stat = "perks_at_5",
        target = 5,
        tier = "silver",
    },
    {
        id = "learn_perks10_3",
        name = "UI_LugliAch_learn_perks10_3_name",
        description = "UI_LugliAch_learn_perks10_3_desc",
        category = "autodidact",
        stat = "perks_at_10",
        target = 3,
        tier = "gold",
    },
    {
        id = "learn_perks1_35",
        name = "UI_LugliAch_learn_perks1_35_name",
        description = "UI_LugliAch_learn_perks1_35_desc",
        category = "autodidact",
        stat = "perks_at_1",
        target = 35,
        tier = "gold",
    },
    {
        id = "learn_books_10",
        name = "UI_LugliAch_learn_books_10_name",
        description = "UI_LugliAch_learn_books_10_desc",
        category = "autodidact",
        stat = "books_read",
        target = 10,
        unit = "UI_LugliAch_unit_books",
        tier = "bronze",
    },
    {
        id = "learn_books_50",
        name = "UI_LugliAch_learn_books_50_name",
        description = "UI_LugliAch_learn_books_50_desc",
        category = "autodidact",
        stat = "books_read",
        target = 50,
        unit = "UI_LugliAch_unit_books",
        tier = "silver",
    },
    {
        id = "learn_books_120",
        name = "UI_LugliAch_learn_books_120_name",
        description = "UI_LugliAch_learn_books_120_desc",
        category = "autodidact",
        stat = "skill_books_read",
        target = 120,
        unit = "UI_LugliAch_unit_books",
        tier = "gold",
    },
    {
        id = "learn_mag_50",
        name = "UI_LugliAch_learn_mag_50_name",
        description = "UI_LugliAch_learn_mag_50_desc",
        category = "autodidact",
        stat = "magazines_read",
        target = 50,
        unit = "UI_LugliAch_unit_magazines",
        tier = "silver",
    },
    {
        id = "learn_recipes_50",
        name = "UI_LugliAch_learn_recipes_50_name",
        description = "UI_LugliAch_learn_recipes_50_desc",
        category = "autodidact",
        stat = "recipes_known",
        target = 50,
        unit = "UI_LugliAch_unit_recipes",
        tier = "bronze",
    },
    {
        id = "learn_recipes_300",
        name = "UI_LugliAch_learn_recipes_300_name",
        description = "UI_LugliAch_learn_recipes_300_desc",
        category = "autodidact",
        stat = "recipes_known",
        target = 300,
        unit = "UI_LugliAch_unit_recipes",
        tier = "gold",
    },
    {
        id = "learn_research_25",
        name = "UI_LugliAch_learn_research_25_name",
        description = "UI_LugliAch_learn_research_25_desc",
        category = "autodidact",
        stat = "recipes_researched",
        target = 25,
        tier = "silver",
    },
    {
        id = "learn_carpentry_10",
        name = "UI_LugliAch_learn_carpentry_10_name",
        description = "UI_LugliAch_learn_carpentry_10_desc",
        category = "autodidact",
        stat = "perk_woodwork",
        target = 10,
        tier = "silver",
    },
    {
        id = "learn_doctor_5",
        name = "UI_LugliAch_learn_doctor_5_name",
        description = "UI_LugliAch_learn_doctor_5_desc",
        category = "autodidact",
        stat = "perk_doctor",
        target = 5,
        tier = "bronze",
    },
    {
        id = "learn_mechanics_7",
        name = "UI_LugliAch_learn_mechanics_7_name",
        description = "UI_LugliAch_learn_mechanics_7_desc",
        category = "autodidact",
        stat = "perk_mechanics",
        target = 7,
        tier = "silver",
    },
    {
        id = "learn_blacksmith_7",
        name = "UI_LugliAch_learn_blacksmith_7_name",
        description = "UI_LugliAch_learn_blacksmith_7_desc",
        category = "autodidact",
        stat = "perk_blacksmith",
        target = 7,
        tier = "silver",
    },
    {
        id = "learn_lose_1",
        name = "UI_LugliAch_learn_lose_1_name",
        description = "UI_LugliAch_learn_lose_1_desc",
        category = "autodidact",
        stat = "perk_levels_lost",
        target = 1,
        tier = "bronze",
    },
    {
        id = "learn_xp_100000",
        name = "UI_LugliAch_learn_xp_100000_name",
        description = "UI_LugliAch_learn_xp_100000_desc",
        category = "autodidact",
        stat = "xp_total",
        target = 100000,
        tier = "silver",
    },
}

for i = 1, #DEFS do
    M.register(DEFS[i])
end

M.status("Autodidact definitions", true)
