require "LugliAchievements/Categories"

local M = LugliAchievements

local DEFS = {
    {
        id = "combat_kill_1",
        name = "UI_LugliAch_combat_kill_1_name",
        description = "UI_LugliAch_combat_kill_1_desc",
        category = "body_count",
        stat = "kills_total",
        target = 1,
        unit = "UI_LugliAch_unit_zombies",
        tier = "bronze",
    },
    {
        id = "combat_kill_100",
        name = "UI_LugliAch_combat_kill_100_name",
        description = "UI_LugliAch_combat_kill_100_desc",
        category = "body_count",
        stat = "kills_total",
        target = 100,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_kill_1000",
        name = "UI_LugliAch_combat_kill_1000_name",
        description = "UI_LugliAch_combat_kill_1000_desc",
        category = "body_count",
        stat = "kills_total",
        target = 1000,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_kill_5000",
        name = "UI_LugliAch_combat_kill_5000_name",
        description = "UI_LugliAch_combat_kill_5000_desc",
        category = "body_count",
        stat = "kills_total",
        target = 5000,
        unit = "UI_LugliAch_unit_zombies",
        tier = "gold",
    },
    {
        id = "combat_kill_10000",
        name = "UI_LugliAch_combat_kill_10000_name",
        description = "UI_LugliAch_combat_kill_10000_desc",
        category = "body_count",
        stat = "kills_total",
        target = 10000,
        unit = "UI_LugliAch_unit_zombies",
        tier = "gold",
    },
    {
        id = "combat_axe_250",
        name = "UI_LugliAch_combat_axe_250_name",
        description = "UI_LugliAch_combat_axe_250_desc",
        category = "body_count",
        stat = "kills_axe",
        target = 250,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_blunt_250",
        name = "UI_LugliAch_combat_blunt_250_name",
        description = "UI_LugliAch_combat_blunt_250_desc",
        category = "body_count",
        stat = "kills_blunt",
        target = 250,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_smallblunt_150",
        name = "UI_LugliAch_combat_smallblunt_150_name",
        description = "UI_LugliAch_combat_smallblunt_150_desc",
        category = "body_count",
        stat = "kills_smallblunt",
        target = 150,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_longblade_150",
        name = "UI_LugliAch_combat_longblade_150_name",
        description = "UI_LugliAch_combat_longblade_150_desc",
        category = "body_count",
        stat = "kills_longblade",
        target = 150,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_smallblade_150",
        name = "UI_LugliAch_combat_smallblade_150_name",
        description = "UI_LugliAch_combat_smallblade_150_desc",
        category = "body_count",
        stat = "kills_smallblade",
        target = 150,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_spear_100",
        name = "UI_LugliAch_combat_spear_100_name",
        description = "UI_LugliAch_combat_spear_100_desc",
        category = "body_count",
        stat = "kills_spear",
        target = 100,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_unarmed_25",
        name = "UI_LugliAch_combat_unarmed_25_name",
        description = "UI_LugliAch_combat_unarmed_25_desc",
        category = "body_count",
        stat = "kills_unarmed",
        target = 25,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_improvised_100",
        name = "UI_LugliAch_combat_improvised_100_name",
        description = "UI_LugliAch_combat_improvised_100_desc",
        category = "body_count",
        stat = "kills_improvised",
        target = 100,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_allclasses_8",
        name = "UI_LugliAch_combat_allclasses_8_name",
        description = "UI_LugliAch_combat_allclasses_8_desc",
        category = "body_count",
        stat = "weapon_classes_used",
        target = 8,
        tier = "silver",
    },
    {
        id = "combat_downed_100",
        name = "UI_LugliAch_combat_downed_100_name",
        description = "UI_LugliAch_combat_downed_100_desc",
        category = "body_count",
        stat = "kills_downed",
        target = 100,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_onehit_100",
        name = "UI_LugliAch_combat_onehit_100_name",
        description = "UI_LugliAch_combat_onehit_100_desc",
        category = "body_count",
        stat = "kills_onehit",
        target = 100,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
    {
        id = "combat_head_500",
        name = "UI_LugliAch_combat_head_500_name",
        description = "UI_LugliAch_combat_head_500_desc",
        category = "body_count",
        stat = "hits_head",
        target = 500,
        tier = "silver",
    },
    {
        id = "combat_crit_250",
        name = "UI_LugliAch_combat_crit_250_name",
        description = "UI_LugliAch_combat_crit_250_desc",
        category = "body_count",
        stat = "hits_crit",
        target = 250,
        tier = "silver",
    },
    {
        id = "combat_walkaway_1",
        name = "UI_LugliAch_combat_walkaway_1_name",
        description = "UI_LugliAch_combat_walkaway_1_desc",
        category = "body_count",
        stat = "no_kill_days",
        target = 1,
        tier = "bronze",
    },
    {
        id = "noise_shot_1",
        name = "UI_LugliAch_noise_shot_1_name",
        description = "UI_LugliAch_noise_shot_1_desc",
        category = "body_count",
        stat = "shots_fired",
        target = 1,
        unit = "UI_LugliAch_unit_shots",
        tier = "bronze",
    },
    {
        id = "noise_shot_100",
        name = "UI_LugliAch_noise_shot_100_name",
        description = "UI_LugliAch_noise_shot_100_desc",
        category = "body_count",
        stat = "shots_fired",
        target = 100,
        unit = "UI_LugliAch_unit_shots",
        tier = "silver",
    },
    {
        id = "noise_shot_1000",
        name = "UI_LugliAch_noise_shot_1000_name",
        description = "UI_LugliAch_noise_shot_1000_desc",
        category = "body_count",
        stat = "shots_fired",
        target = 1000,
        unit = "UI_LugliAch_unit_shots",
        tier = "silver",
    },
    {
        id = "noise_gunkill_1",
        name = "UI_LugliAch_noise_gunkill_1_name",
        description = "UI_LugliAch_noise_gunkill_1_desc",
        category = "body_count",
        stat = "kills_firearm",
        target = 1,
        unit = "UI_LugliAch_unit_zombies",
        tier = "bronze",
    },
    {
        id = "noise_gunkill_500",
        name = "UI_LugliAch_noise_gunkill_500_name",
        description = "UI_LugliAch_noise_gunkill_500_desc",
        category = "body_count",
        stat = "kills_firearm",
        target = 500,
        unit = "UI_LugliAch_unit_zombies",
        tier = "gold",
    },
    {
        id = "noise_guns_22",
        name = "UI_LugliAch_noise_guns_22_name",
        description = "UI_LugliAch_noise_guns_22_desc",
        category = "body_count",
        stat = "firearms_fired",
        target = 22,
        tier = "silver",
    },
    {
        id = "noise_reload_100",
        name = "UI_LugliAch_noise_reload_100_name",
        description = "UI_LugliAch_noise_reload_100_desc",
        category = "body_count",
        stat = "reloads",
        target = 100,
        tier = "silver",
    },
    {
        id = "noise_rack_50",
        name = "UI_LugliAch_noise_rack_50_name",
        description = "UI_LugliAch_noise_rack_50_desc",
        category = "body_count",
        stat = "racks",
        target = 50,
        tier = "silver",
    },
    {
        id = "noise_upgrade_10",
        name = "UI_LugliAch_noise_upgrade_10_name",
        description = "UI_LugliAch_noise_upgrade_10_desc",
        category = "body_count",
        stat = "weapon_upgrades",
        target = 10,
        tier = "silver",
    },
    {
        id = "noise_boom_1",
        name = "UI_LugliAch_noise_boom_1_name",
        description = "UI_LugliAch_noise_boom_1_desc",
        category = "body_count",
        stat = "explosions",
        target = 1,
        tier = "bronze",
    },
    {
        id = "noise_boom_25",
        name = "UI_LugliAch_noise_boom_25_name",
        description = "UI_LugliAch_noise_boom_25_desc",
        category = "body_count",
        stat = "explosions",
        target = 25,
        tier = "silver",
    },
    {
        id = "noise_alarm_10",
        name = "UI_LugliAch_noise_alarm_10_name",
        description = "UI_LugliAch_noise_alarm_10_desc",
        category = "body_count",
        stat = "alarms_survived",
        target = 10,
        tier = "silver",
    },
}

for i = 1, #DEFS do
    M.register(DEFS[i])
end

M.status("Body Count definitions", true)
