require "LugliAchievements/Categories"
require "LugliAchievements/Challenge"

local M = LugliAchievements

-- Situations rather than totals. Every row here is an ordinary achievement definition: the only
-- new field is `when`, and it still unlocks on stats[stat] >= target like the other 258.
--
-- `stat` is written out even though it looks derivable from `id`. It has to be: the gate, the
-- README roster, the Workshop listing and the icon prompts all read these files with one regex,
-- and a key that only exists at runtime is invisible to every one of them.
local DEFS = {
    -- Your own state at the moment of the kill.
    {
        id = "chal_hurt_kill",
        name = "UI_LugliAch_chal_hurt_kill_name",
        description = "UI_LugliAch_chal_hurt_kill_desc",
        category = "challenges",
        stat = "chal_hurt_kill",
        target = 1,
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "health_pct", "<", 25 } },
            count = "once",
        },
    },
    {
        id = "chal_panic_kills_10",
        name = "UI_LugliAch_chal_panic_kills_10_name",
        description = "UI_LugliAch_chal_panic_kills_10_desc",
        category = "challenges",
        stat = "chal_panic_kills",
        target = 10,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "moodle_panic", ">=", 4 } },
            count = "each",
        },
    },
    {
        id = "chal_fracture_kills_5",
        name = "UI_LugliAch_chal_fracture_kills_5_name",
        description = "UI_LugliAch_chal_fracture_kills_5_desc",
        category = "challenges",
        stat = "chal_fracture_kills",
        target = 5,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "leg_fractured", "==", true } },
            count = "each",
        },
    },
    {
        id = "chal_drunk_kills_20",
        name = "UI_LugliAch_chal_drunk_kills_20_name",
        description = "UI_LugliAch_chal_drunk_kills_20_desc",
        category = "challenges",
        stat = "chal_drunk_kills",
        target = 20,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "moodle_drunk", ">=", 2 } },
            count = "each",
        },
    },
    {
        id = "chal_burning_kill",
        name = "UI_LugliAch_chal_burning_kill_name",
        description = "UI_LugliAch_chal_burning_kill_desc",
        category = "challenges",
        stat = "chal_burning_kill",
        target = 1,
        tier = "gold",
        when = {
            trigger = "zombie_killed",
            all = { { "on_fire", "==", true } },
            count = "once",
        },
    },
    {
        id = "chal_spent_kills_20",
        name = "UI_LugliAch_chal_spent_kills_20_name",
        description = "UI_LugliAch_chal_spent_kills_20_desc",
        category = "challenges",
        stat = "chal_spent_kills",
        target = 20,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "moodle_endurance", ">=", 3 } },
            count = "each",
        },
    },
    {
        id = "chal_heavy_kills_10",
        name = "UI_LugliAch_chal_heavy_kills_10_name",
        description = "UI_LugliAch_chal_heavy_kills_10_desc",
        category = "challenges",
        stat = "chal_heavy_kills",
        target = 10,
        unit = "UI_LugliAch_unit_zombies",
        tier = "bronze",
        when = {
            trigger = "zombie_killed",
            all = { { "moodle_heavy", ">=", 3 } },
            count = "each",
        },
    },
    {
        id = "chal_bleeding_kills_20",
        name = "UI_LugliAch_chal_bleeding_kills_20_name",
        description = "UI_LugliAch_chal_bleeding_kills_20_desc",
        category = "challenges",
        stat = "chal_bleeding_kills",
        target = 20,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "bleeding_parts", ">=", 2 } },
            count = "each",
        },
    },
    {
        id = "chal_sneak_kills_25",
        name = "UI_LugliAch_chal_sneak_kills_25_name",
        description = "UI_LugliAch_chal_sneak_kills_25_desc",
        category = "challenges",
        stat = "chal_sneak_kills",
        target = 25,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "sneaking", "==", true } },
            count = "each",
        },
    },
    {
        id = "chal_night_kills_100",
        name = "UI_LugliAch_chal_night_kills_100_name",
        description = "UI_LugliAch_chal_night_kills_100_desc",
        category = "challenges",
        stat = "chal_night_kills",
        target = 100,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "night", "==", true } },
            count = "each",
        },
    },
    {
        id = "chal_aimed_pressure_15",
        name = "UI_LugliAch_chal_aimed_pressure_15_name",
        description = "UI_LugliAch_chal_aimed_pressure_15_desc",
        category = "challenges",
        stat = "chal_aimed_pressure",
        target = 15,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "aiming", "==", true }, { "chasing", ">=", 3 } },
            count = "each",
        },
    },

    -- The crowd around you. Every one of these reads getNumChasingZombies, which the engine
    -- maintains anyway and vanilla itself calls in ISSearchManager.
    {
        id = "chal_window_chased_3",
        name = "UI_LugliAch_chal_window_chased_3_name",
        description = "UI_LugliAch_chal_window_chased_3_desc",
        category = "challenges",
        stat = "chal_window_chased",
        target = 3,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = { trigger = "window_climbed", count = "best", value = "chasing" },
    },
    {
        id = "chal_fence_chased_5",
        name = "UI_LugliAch_chal_fence_chased_5_name",
        description = "UI_LugliAch_chal_fence_chased_5_desc",
        category = "challenges",
        stat = "chal_fence_chased",
        target = 5,
        unit = "UI_LugliAch_unit_zombies",
        tier = "gold",
        when = { trigger = "fence_climbed", count = "best", value = "chasing" },
    },
    {
        id = "chal_rope_chased_3",
        name = "UI_LugliAch_chal_rope_chased_3_name",
        description = "UI_LugliAch_chal_rope_chased_3_desc",
        category = "challenges",
        stat = "chal_rope_chased",
        target = 3,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = { trigger = "rope_climbed", count = "best", value = "chasing" },
    },
    {
        id = "chal_car_chased_8",
        name = "UI_LugliAch_chal_car_chased_8_name",
        description = "UI_LugliAch_chal_car_chased_8_desc",
        category = "challenges",
        stat = "chal_car_chased",
        target = 8,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = { trigger = "vehicle_entered", count = "best", value = "chasing" },
    },
    {
        id = "chal_bandage_chased_3",
        name = "UI_LugliAch_chal_bandage_chased_3_name",
        description = "UI_LugliAch_chal_bandage_chased_3_desc",
        category = "challenges",
        stat = "chal_bandage_chased",
        target = 3,
        unit = "UI_LugliAch_unit_zombies",
        tier = "gold",
        when = { trigger = "bandaged", count = "best", value = "chasing" },
    },
    {
        id = "chal_crowd_kill_15",
        name = "UI_LugliAch_chal_crowd_kill_15_name",
        description = "UI_LugliAch_chal_crowd_kill_15_desc",
        category = "challenges",
        stat = "chal_crowd_kill",
        target = 15,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = { trigger = "zombie_killed", count = "best", value = "visible" },
    },
    {
        id = "chal_heavy_fence",
        name = "UI_LugliAch_chal_heavy_fence_name",
        description = "UI_LugliAch_chal_heavy_fence_desc",
        category = "challenges",
        stat = "chal_heavy_fence",
        target = 1,
        tier = "bronze",
        when = {
            trigger = "fence_climbed",
            all = { { "moodle_heavy", ">=", 3 } },
            count = "once",
        },
    },

    -- Tempo. Nothing here is a bigger number, it is the same number in less time.
    {
        id = "chal_burst_5_10s",
        name = "UI_LugliAch_chal_burst_5_10s_name",
        description = "UI_LugliAch_chal_burst_5_10s_desc",
        category = "challenges",
        stat = "chal_burst_5_10s",
        target = 1,
        tier = "gold",
        when = { trigger = "zombie_killed", count = "burst", window = 10, need = 5 },
    },
    {
        id = "chal_burst_3_3s",
        name = "UI_LugliAch_chal_burst_3_3s_name",
        description = "UI_LugliAch_chal_burst_3_3s_desc",
        category = "challenges",
        stat = "chal_burst_3_3s",
        target = 1,
        tier = "silver",
        when = { trigger = "zombie_killed", count = "burst", window = 3, need = 3 },
    },
    {
        id = "chal_untouched_50",
        name = "UI_LugliAch_chal_untouched_50_name",
        description = "UI_LugliAch_chal_untouched_50_desc",
        category = "challenges",
        stat = "chal_untouched_best",
        target = 50,
        unit = "UI_LugliAch_unit_zombies",
        tier = "gold",
        when = {
            trigger = "zombie_killed",
            count = "streak",
            reset = { trigger = "player_struck" },
        },
    },
    {
        id = "chal_life_kills_100",
        name = "UI_LugliAch_chal_life_kills_100_name",
        description = "UI_LugliAch_chal_life_kills_100_desc",
        category = "challenges",
        stat = "chal_life_kills_best",
        target = 100,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
        when = { trigger = "zombie_killed", count = "life" },
    },

    -- The situation itself.
    {
        id = "chal_feeding_kill",
        name = "UI_LugliAch_chal_feeding_kill_name",
        description = "UI_LugliAch_chal_feeding_kill_desc",
        category = "challenges",
        stat = "chal_feeding_kill",
        target = 1,
        tier = "bronze",
        when = {
            trigger = "zombie_killed",
            all = { { "zombie_feeding", "==", true } },
            count = "once",
        },
    },
    {
        id = "chal_reanimated_kill",
        name = "UI_LugliAch_chal_reanimated_kill_name",
        description = "UI_LugliAch_chal_reanimated_kill_desc",
        category = "challenges",
        stat = "chal_reanimated_kill",
        target = 1,
        tier = "silver",
        when = {
            trigger = "zombie_killed",
            all = { { "zombie_reanimated", "==", true } },
            count = "once",
        },
    },
    {
        id = "chal_widenet_10",
        name = "UI_LugliAch_chal_widenet_10_name",
        description = "UI_LugliAch_chal_widenet_10_desc",
        category = "challenges",
        stat = "chal_widenet",
        target = 10,
        unit = "UI_LugliAch_unit_types",
        tier = "gold",
        when = {
            trigger = "zombie_killed",
            all = { { "health_pct", "<", 50 } },
            count = "unique",
            uniqueBy = "weapon_type",
        },
    },
}

for i = 1, #DEFS do
    if M.register(DEFS[i]) then M.declareChallenge(DEFS[i]) end
end

M.status("Challenge definitions", true)
