require "LugliAchievements/Categories"

local M = LugliAchievements

local DEFS = {
    {
        id = "farm_harvest_1",
        name = "UI_LugliAch_farm_harvest_1_name",
        description = "UI_LugliAch_farm_harvest_1_desc",
        category = "homestead",
        stat = "crops_harvested",
        target = 1,
        unit = "UI_LugliAch_unit_crops",
        tier = "bronze",
    },
    {
        id = "farm_harvest_50",
        name = "UI_LugliAch_farm_harvest_50_name",
        description = "UI_LugliAch_farm_harvest_50_desc",
        category = "homestead",
        stat = "crops_harvested",
        target = 50,
        unit = "UI_LugliAch_unit_crops",
        tier = "silver",
    },
    {
        id = "farm_plant_25",
        name = "UI_LugliAch_farm_plant_25_name",
        description = "UI_LugliAch_farm_plant_25_desc",
        category = "homestead",
        stat = "seeds_planted",
        target = 25,
        tier = "silver",
    },
    {
        id = "farm_crops_12",
        name = "UI_LugliAch_farm_crops_12_name",
        description = "UI_LugliAch_farm_crops_12_desc",
        category = "homestead",
        stat = "crop_types",
        target = 12,
        tier = "silver",
    },
    {
        id = "farm_water_100",
        name = "UI_LugliAch_farm_water_100_name",
        description = "UI_LugliAch_farm_water_100_desc",
        category = "homestead",
        stat = "plants_watered",
        target = 100,
        tier = "silver",
    },
    {
        id = "farm_compost_25",
        name = "UI_LugliAch_farm_compost_25_name",
        description = "UI_LugliAch_farm_compost_25_desc",
        category = "homestead",
        stat = "compost_added",
        target = 25,
        tier = "silver",
    },
    {
        id = "farm_scythe_100",
        name = "UI_LugliAch_farm_scythe_100_name",
        description = "UI_LugliAch_farm_scythe_100_desc",
        category = "homestead",
        stat = "scythings",
        target = 100,
        tier = "silver",
    },
    {
        id = "farm_tree_100",
        name = "UI_LugliAch_farm_tree_100_name",
        description = "UI_LugliAch_farm_tree_100_desc",
        category = "homestead",
        stat = "trees_chopped",
        target = 100,
        tier = "silver",
    },
    {
        id = "farm_fish_1",
        name = "UI_LugliAch_farm_fish_1_name",
        description = "UI_LugliAch_farm_fish_1_desc",
        category = "homestead",
        stat = "fish_caught",
        target = 1,
        unit = "UI_LugliAch_unit_fish",
        tier = "bronze",
    },
    {
        id = "farm_fish_50",
        name = "UI_LugliAch_farm_fish_50_name",
        description = "UI_LugliAch_farm_fish_50_desc",
        category = "homestead",
        stat = "fish_caught",
        target = 50,
        unit = "UI_LugliAch_unit_fish",
        tier = "silver",
    },
    {
        id = "farm_species_20",
        name = "UI_LugliAch_farm_species_20_name",
        description = "UI_LugliAch_farm_species_20_desc",
        category = "homestead",
        stat = "fish_species",
        target = 20,
        tier = "silver",
    },
    {
        id = "farm_net_25",
        name = "UI_LugliAch_farm_net_25_name",
        description = "UI_LugliAch_farm_net_25_desc",
        category = "homestead",
        stat = "nets_checked",
        target = 25,
        tier = "silver",
    },
    {
        id = "farm_trap_1",
        name = "UI_LugliAch_farm_trap_1_name",
        description = "UI_LugliAch_farm_trap_1_desc",
        category = "homestead",
        stat = "traps_placed",
        target = 1,
        tier = "bronze",
    },
    {
        id = "farm_traps_6",
        name = "UI_LugliAch_farm_traps_6_name",
        description = "UI_LugliAch_farm_traps_6_desc",
        category = "homestead",
        stat = "trap_types",
        target = 6,
        tier = "silver",
    },
    {
        id = "farm_foodtypes_20",
        name = "UI_LugliAch_farm_foodtypes_20_name",
        description = "UI_LugliAch_farm_foodtypes_20_desc",
        category = "homestead",
        stat = "food_types",
        target = 20,
        tier = "bronze",
    },
    {
        id = "farm_foodtypes_40",
        name = "UI_LugliAch_farm_foodtypes_40_name",
        description = "UI_LugliAch_farm_foodtypes_40_desc",
        category = "homestead",
        stat = "food_types",
        target = 40,
        tier = "gold",
    },
    {
        id = "farm_cook_100",
        name = "UI_LugliAch_farm_cook_100_name",
        description = "UI_LugliAch_farm_cook_100_desc",
        category = "homestead",
        stat = "meals_cooked",
        target = 100,
        tier = "silver",
    },
    {
        id = "farm_forage_500",
        name = "UI_LugliAch_farm_forage_500_name",
        description = "UI_LugliAch_farm_forage_500_desc",
        category = "homestead",
        stat = "items_foraged",
        target = 500,
        unit = "UI_LugliAch_unit_items",
        tier = "gold",
    },
    {
        id = "animal_pet_1",
        name = "UI_LugliAch_animal_pet_1_name",
        description = "UI_LugliAch_animal_pet_1_desc",
        category = "homestead",
        stat = "animals_petted",
        target = 1,
        tier = "bronze",
    },
    {
        id = "animal_feed_50",
        name = "UI_LugliAch_animal_feed_50_name",
        description = "UI_LugliAch_animal_feed_50_desc",
        category = "homestead",
        stat = "animals_fed",
        target = 50,
        tier = "silver",
    },
    {
        id = "animal_milk_1",
        name = "UI_LugliAch_animal_milk_1_name",
        description = "UI_LugliAch_animal_milk_1_desc",
        category = "homestead",
        stat = "animals_milked",
        target = 1,
        tier = "bronze",
    },
    {
        id = "animal_milk_100",
        name = "UI_LugliAch_animal_milk_100_name",
        description = "UI_LugliAch_animal_milk_100_desc",
        category = "homestead",
        stat = "animals_milked",
        target = 100,
        tier = "gold",
    },
    {
        id = "animal_shear_25",
        name = "UI_LugliAch_animal_shear_25_name",
        description = "UI_LugliAch_animal_shear_25_desc",
        category = "homestead",
        stat = "animals_sheared",
        target = 25,
        tier = "silver",
    },
    {
        id = "animal_egg_100",
        name = "UI_LugliAch_animal_egg_100_name",
        description = "UI_LugliAch_animal_egg_100_desc",
        category = "homestead",
        stat = "eggs_collected",
        target = 100,
        tier = "silver",
    },
    {
        id = "animal_butcher_1",
        name = "UI_LugliAch_animal_butcher_1_name",
        description = "UI_LugliAch_animal_butcher_1_desc",
        category = "homestead",
        stat = "animals_butchered",
        target = 1,
        tier = "bronze",
    },
    {
        id = "animal_butcher_50",
        name = "UI_LugliAch_animal_butcher_50_name",
        description = "UI_LugliAch_animal_butcher_50_desc",
        category = "homestead",
        stat = "animals_butchered",
        target = 50,
        tier = "gold",
    },
    {
        id = "animal_leather_25",
        name = "UI_LugliAch_animal_leather_25_name",
        description = "UI_LugliAch_animal_leather_25_desc",
        category = "homestead",
        stat = "leather_taken",
        target = 25,
        tier = "silver",
    },
    {
        id = "animal_bones_50",
        name = "UI_LugliAch_animal_bones_50_name",
        description = "UI_LugliAch_animal_bones_50_desc",
        category = "homestead",
        stat = "bones_taken",
        target = 50,
        tier = "silver",
    },
    {
        id = "animal_hutch_1",
        name = "UI_LugliAch_animal_hutch_1_name",
        description = "UI_LugliAch_animal_hutch_1_desc",
        category = "homestead",
        stat = "animals_hutched",
        target = 1,
        tier = "bronze",
    },
    {
        id = "animal_lure_10",
        name = "UI_LugliAch_animal_lure_10_name",
        description = "UI_LugliAch_animal_lure_10_desc",
        category = "homestead",
        stat = "animals_lured",
        target = 10,
        tier = "silver",
    },
    {
        id = "animal_trailer_1",
        name = "UI_LugliAch_animal_trailer_1_name",
        description = "UI_LugliAch_animal_trailer_1_desc",
        category = "homestead",
        stat = "animals_trailered",
        target = 1,
        tier = "bronze",
    },
    {
        id = "animal_species_10",
        name = "UI_LugliAch_animal_species_10_name",
        description = "UI_LugliAch_animal_species_10_desc",
        category = "homestead",
        stat = "animal_species",
        target = 10,
        tier = "silver",
    },
    {
        id = "animal_track_25",
        name = "UI_LugliAch_animal_track_25_name",
        description = "UI_LugliAch_animal_track_25_desc",
        category = "homestead",
        stat = "tracks_read",
        target = 25,
        tier = "silver",
    },
    {
        id = "animal_hook_10",
        name = "UI_LugliAch_animal_hook_10_name",
        description = "UI_LugliAch_animal_hook_10_desc",
        category = "homestead",
        stat = "animals_hooked",
        target = 10,
        tier = "silver",
    },
    {
        id = "farm_insect_1",
        name = "UI_LugliAch_farm_insect_1_name",
        description = "UI_LugliAch_farm_insect_1_desc",
        category = "homestead",
        stat = "insects_eaten",
        target = 1,
        tier = "bronze",
    },
}

for i = 1, #DEFS do
    M.register(DEFS[i])
end

M.status("Homestead definitions", true)
