require "LugliAchievements/Categories"

local M = LugliAchievements

local DEFS = {
    {
        id = "grave_bury_1",
        name = "UI_LugliAch_grave_bury_1_name",
        description = "UI_LugliAch_grave_bury_1_desc",
        category = "house_proud",
        stat = "corpses_buried",
        target = 1,
        tier = "bronze",
    },
    {
        id = "grave_bury_50",
        name = "UI_LugliAch_grave_bury_50_name",
        description = "UI_LugliAch_grave_bury_50_desc",
        category = "house_proud",
        stat = "corpses_buried",
        target = 50,
        tier = "silver",
    },
    {
        id = "grave_burn_100",
        name = "UI_LugliAch_grave_burn_100_name",
        description = "UI_LugliAch_grave_burn_100_desc",
        category = "house_proud",
        stat = "corpses_burned",
        target = 100,
        tier = "silver",
    },
    {
        id = "grave_window_10",
        name = "UI_LugliAch_grave_window_10_name",
        description = "UI_LugliAch_grave_window_10_desc",
        category = "house_proud",
        stat = "corpses_windowed",
        target = 10,
        tier = "silver",
    },
    {
        id = "grave_fence_10",
        name = "UI_LugliAch_grave_fence_10_name",
        description = "UI_LugliAch_grave_fence_10_desc",
        category = "house_proud",
        stat = "corpses_fenced",
        target = 10,
        tier = "silver",
    },
    {
        id = "grave_move_25",
        name = "UI_LugliAch_grave_move_25_name",
        description = "UI_LugliAch_grave_move_25_desc",
        category = "house_proud",
        stat = "corpses_moved",
        target = 25,
        tier = "silver",
    },
    {
        id = "grave_container_5",
        name = "UI_LugliAch_grave_container_5_name",
        description = "UI_LugliAch_grave_container_5_desc",
        category = "house_proud",
        stat = "corpses_binned",
        target = 5,
        tier = "silver",
    },
    {
        id = "hoard_container_100",
        name = "UI_LugliAch_hoard_container_100_name",
        description = "UI_LugliAch_hoard_container_100_desc",
        category = "house_proud",
        stat = "heaviest_container",
        target = 100,
        tier = "bronze",
    },
    {
        id = "hoard_container_150",
        name = "UI_LugliAch_hoard_container_150_name",
        description = "UI_LugliAch_hoard_container_150_desc",
        category = "house_proud",
        stat = "heaviest_container",
        target = 150,
        tier = "gold",
    },
    {
        id = "hoard_types_100",
        name = "UI_LugliAch_hoard_types_100_name",
        description = "UI_LugliAch_hoard_types_100_desc",
        category = "house_proud",
        stat = "item_types",
        target = 100,
        unit = "UI_LugliAch_unit_types",
        tier = "bronze",
    },
    {
        id = "hoard_types_500",
        name = "UI_LugliAch_hoard_types_500_name",
        description = "UI_LugliAch_hoard_types_500_desc",
        category = "house_proud",
        stat = "item_types",
        target = 500,
        unit = "UI_LugliAch_unit_types",
        tier = "gold",
    },
    {
        id = "hoard_found_1000",
        name = "UI_LugliAch_hoard_found_1000_name",
        description = "UI_LugliAch_hoard_found_1000_desc",
        category = "house_proud",
        stat = "items_acquired",
        target = 1000,
        unit = "UI_LugliAch_unit_items",
        tier = "bronze",
    },
    {
        id = "hoard_found_10000",
        name = "UI_LugliAch_hoard_found_10000_name",
        description = "UI_LugliAch_hoard_found_10000_desc",
        category = "house_proud",
        stat = "items_acquired",
        target = 10000,
        unit = "UI_LugliAch_unit_items",
        tier = "gold",
    },
    {
        id = "hoard_macho_1",
        name = "UI_LugliAch_hoard_macho_1_name",
        description = "UI_LugliAch_hoard_macho_1_desc",
        category = "house_proud",
        stat = "macho",
        target = 1,
        tier = "bronze",
    },
    {
        id = "hoard_overburden_50",
        name = "UI_LugliAch_hoard_overburden_50_name",
        description = "UI_LugliAch_hoard_overburden_50_desc",
        category = "house_proud",
        stat = "overburdened",
        target = 50,
        tier = "silver",
    },
    {
        id = "hoard_consolidate_100",
        name = "UI_LugliAch_hoard_consolidate_100_name",
        description = "UI_LugliAch_hoard_consolidate_100_desc",
        category = "house_proud",
        stat = "consolidations",
        target = 100,
        tier = "silver",
    },
    {
        id = "hoard_dump_50",
        name = "UI_LugliAch_hoard_dump_50_name",
        description = "UI_LugliAch_hoard_dump_50_desc",
        category = "house_proud",
        stat = "containers_dumped",
        target = 50,
        tier = "silver",
    },
    {
        id = "hoard_sledge_1",
        name = "UI_LugliAch_hoard_sledge_1_name",
        description = "UI_LugliAch_hoard_sledge_1_desc",
        category = "house_proud",
        stat = "saw_sledgehammer",
        target = 1,
        tier = "bronze",
    },
    {
        id = "house_blood_1",
        name = "UI_LugliAch_house_blood_1_name",
        description = "UI_LugliAch_house_blood_1_desc",
        category = "house_proud",
        stat = "blood_cleaned",
        target = 1,
        tier = "bronze",
    },
    {
        id = "house_blood_500",
        name = "UI_LugliAch_house_blood_500_name",
        description = "UI_LugliAch_house_blood_500_desc",
        category = "house_proud",
        stat = "blood_cleaned",
        target = 500,
        tier = "gold",
    },
    {
        id = "house_graffiti_25",
        name = "UI_LugliAch_house_graffiti_25_name",
        description = "UI_LugliAch_house_graffiti_25_desc",
        category = "house_proud",
        stat = "graffiti_cleaned",
        target = 25,
        tier = "silver",
    },
    {
        id = "house_wash_self_50",
        name = "UI_LugliAch_house_wash_self_50_name",
        description = "UI_LugliAch_house_wash_self_50_desc",
        category = "house_proud",
        stat = "washes",
        target = 50,
        tier = "silver",
    },
    {
        id = "house_wash_clothes_100",
        name = "UI_LugliAch_house_wash_clothes_100_name",
        description = "UI_LugliAch_house_wash_clothes_100_desc",
        category = "house_proud",
        stat = "clothes_washed",
        target = 100,
        tier = "silver",
    },
    {
        id = "house_repair_50",
        name = "UI_LugliAch_house_repair_50_name",
        description = "UI_LugliAch_house_repair_50_desc",
        category = "house_proud",
        stat = "clothes_repaired",
        target = 50,
        tier = "silver",
    },
    {
        id = "house_haircut_1",
        name = "UI_LugliAch_house_haircut_1_name",
        description = "UI_LugliAch_house_haircut_1_desc",
        category = "house_proud",
        stat = "haircuts",
        target = 1,
        tier = "bronze",
    },
    {
        id = "house_dye_1",
        name = "UI_LugliAch_house_dye_1_name",
        description = "UI_LugliAch_house_dye_1_desc",
        category = "house_proud",
        stat = "hair_dyed",
        target = 1,
        tier = "bronze",
    },
    {
        id = "house_beard_10",
        name = "UI_LugliAch_house_beard_10_name",
        description = "UI_LugliAch_house_beard_10_desc",
        category = "house_proud",
        stat = "beard_trims",
        target = 10,
        tier = "silver",
    },
    {
        id = "house_makeup_1",
        name = "UI_LugliAch_house_makeup_1_name",
        description = "UI_LugliAch_house_makeup_1_desc",
        category = "house_proud",
        stat = "makeup_applied",
        target = 1,
        tier = "bronze",
    },
    {
        id = "house_curtain_50",
        name = "UI_LugliAch_house_curtain_50_name",
        description = "UI_LugliAch_house_curtain_50_desc",
        category = "house_proud",
        stat = "curtains_used",
        target = 50,
        tier = "silver",
    },
    {
        id = "house_light_100",
        name = "UI_LugliAch_house_light_100_name",
        description = "UI_LugliAch_house_light_100_desc",
        category = "house_proud",
        stat = "lights_toggled",
        target = 100,
        tier = "silver",
    },
    {
        id = "house_write_10",
        name = "UI_LugliAch_house_write_10_name",
        description = "UI_LugliAch_house_write_10_desc",
        category = "house_proud",
        stat = "notes_written",
        target = 10,
        tier = "silver",
    },
}

for i = 1, #DEFS do
    M.register(DEFS[i])
end

M.status("House Proud definitions", true)
