-- Every row here is earned by dying, which is why per-world is the default progress scope.
require "LugliAchievements/Categories"

local M = LugliAchievements

local DEFS = {
    {
        id = "died_1",
        name = "UI_LugliAch_died_1_name",
        description = "UI_LugliAch_died_1_desc",
        category = "how_you_died",
        stat = "deaths",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_day_1",
        name = "UI_LugliAch_died_day_1_name",
        description = "UI_LugliAch_died_day_1_desc",
        category = "how_you_died",
        stat = "died_day_one",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_bathroom",
        name = "UI_LugliAch_died_bathroom_name",
        description = "UI_LugliAch_died_bathroom_desc",
        category = "how_you_died",
        stat = "died_bathroom",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_crash",
        name = "UI_LugliAch_died_crash_name",
        description = "UI_LugliAch_died_crash_desc",
        category = "how_you_died",
        stat = "died_crash",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_fire",
        name = "UI_LugliAch_died_fire_name",
        description = "UI_LugliAch_died_fire_desc",
        category = "how_you_died",
        stat = "died_fire",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_fall",
        name = "UI_LugliAch_died_fall_name",
        description = "UI_LugliAch_died_fall_desc",
        category = "how_you_died",
        stat = "died_fall",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_thirst",
        name = "UI_LugliAch_died_thirst_name",
        description = "UI_LugliAch_died_thirst_desc",
        category = "how_you_died",
        stat = "died_thirst",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_hunger",
        name = "UI_LugliAch_died_hunger_name",
        description = "UI_LugliAch_died_hunger_desc",
        category = "how_you_died",
        stat = "died_hunger",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_poison",
        name = "UI_LugliAch_died_poison_name",
        description = "UI_LugliAch_died_poison_desc",
        category = "how_you_died",
        stat = "died_poison",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_sick",
        name = "UI_LugliAch_died_sick_name",
        description = "UI_LugliAch_died_sick_desc",
        category = "how_you_died",
        stat = "died_infection",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_bleed",
        name = "UI_LugliAch_died_bleed_name",
        description = "UI_LugliAch_died_bleed_desc",
        category = "how_you_died",
        stat = "died_bleeding",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_cold",
        name = "UI_LugliAch_died_cold_name",
        description = "UI_LugliAch_died_cold_desc",
        category = "how_you_died",
        stat = "died_cold",
        target = 1,
        tier = "bronze",
    },
    {
        id = "died_outside_town",
        name = "UI_LugliAch_died_outside_town_name",
        description = "UI_LugliAch_died_outside_town_desc",
        category = "how_you_died",
        stat = "died_wilderness",
        target = 1,
        tier = "silver",
    },
    {
        id = "died_animal",
        name = "UI_LugliAch_died_animal_name",
        description = "UI_LugliAch_died_animal_desc",
        category = "how_you_died",
        stat = "died_animal",
        target = 1,
        tier = "silver",
    },
    {
        id = "died_after_year",
        name = "UI_LugliAch_died_after_year_name",
        description = "UI_LugliAch_died_after_year_desc",
        category = "how_you_died",
        stat = "died_veteran",
        target = 1,
        tier = "silver",
    },
    {
        id = "died_zombified",
        name = "UI_LugliAch_died_zombified_name",
        description = "UI_LugliAch_died_zombified_desc",
        category = "how_you_died",
        stat = "died_zombified",
        target = 1,
        tier = "silver",
    },
    {
        id = "died_bleach",
        name = "UI_LugliAch_died_bleach_name",
        description = "UI_LugliAch_died_bleach_desc",
        category = "how_you_died",
        stat = "died_bleach",
        target = 1,
        tier = "bronze",
    },
}

for i = 1, #DEFS do
    M.register(DEFS[i])
end

M.status("This Is How You Died definitions", true)
