require "LugliAchievements/Categories"

local M = LugliAchievements

local DEFS = {
    {
        id = "fire_light_1",
        name = "UI_LugliAch_fire_light_1_name",
        description = "UI_LugliAch_fire_light_1_desc",
        category = "nailed_it",
        stat = "fires_lit",
        target = 1,
        tier = "bronze",
    },
    {
        id = "fire_literature_1",
        name = "UI_LugliAch_fire_literature_1_name",
        description = "UI_LugliAch_fire_literature_1_desc",
        category = "nailed_it",
        stat = "fires_from_books",
        target = 1,
        tier = "bronze",
    },
    {
        id = "fire_petrol_10",
        name = "UI_LugliAch_fire_petrol_10_name",
        description = "UI_LugliAch_fire_petrol_10_desc",
        category = "nailed_it",
        stat = "fires_from_petrol",
        target = 10,
        tier = "silver",
    },
    {
        id = "fire_out_25",
        name = "UI_LugliAch_fire_out_25_name",
        description = "UI_LugliAch_fire_out_25_desc",
        category = "nailed_it",
        stat = "fires_extinguished",
        target = 25,
        tier = "silver",
    },
    {
        id = "fire_candle_50",
        name = "UI_LugliAch_fire_candle_50_name",
        description = "UI_LugliAch_fire_candle_50_desc",
        category = "nailed_it",
        stat = "candles_snuffed",
        target = 50,
        tier = "silver",
    },
    {
        id = "fire_ashes_25",
        name = "UI_LugliAch_fire_ashes_25_name",
        description = "UI_LugliAch_fire_ashes_25_desc",
        category = "nailed_it",
        stat = "ashes_cleared",
        target = 25,
        tier = "silver",
    },
    {
        id = "fire_bbq_100",
        name = "UI_LugliAch_fire_bbq_100_name",
        description = "UI_LugliAch_fire_bbq_100_desc",
        category = "nailed_it",
        stat = "bbq_uses",
        target = 100,
        tier = "silver",
    },
    {
        id = "fire_molotov_25",
        name = "UI_LugliAch_fire_molotov_25_name",
        description = "UI_LugliAch_fire_molotov_25_desc",
        category = "nailed_it",
        stat = "molotovs_thrown",
        target = 25,
        tier = "silver",
    },
    {
        id = "fire_selfless_1",
        name = "UI_LugliAch_fire_selfless_1_name",
        description = "UI_LugliAch_fire_selfless_1_desc",
        category = "nailed_it",
        stat = "survived_fire",
        target = 1,
        tier = "bronze",
    },
    {
        id = "build_things_10",
        name = "UI_LugliAch_build_things_10_name",
        description = "UI_LugliAch_build_things_10_desc",
        category = "nailed_it",
        stat = "objects_built",
        target = 10,
        unit = "UI_LugliAch_unit_things",
        tier = "bronze",
    },
    {
        id = "build_things_100",
        name = "UI_LugliAch_build_things_100_name",
        description = "UI_LugliAch_build_things_100_desc",
        category = "nailed_it",
        stat = "objects_built",
        target = 100,
        unit = "UI_LugliAch_unit_things",
        tier = "silver",
    },
    {
        id = "build_things_500",
        name = "UI_LugliAch_build_things_500_name",
        description = "UI_LugliAch_build_things_500_desc",
        category = "nailed_it",
        stat = "objects_built",
        target = 500,
        unit = "UI_LugliAch_unit_things",
        tier = "gold",
    },
    {
        id = "build_barricade_10",
        name = "UI_LugliAch_build_barricade_10_name",
        description = "UI_LugliAch_build_barricade_10_desc",
        category = "nailed_it",
        stat = "barricades_built",
        target = 10,
        tier = "bronze",
    },
    {
        id = "build_barricade_50",
        name = "UI_LugliAch_build_barricade_50_name",
        description = "UI_LugliAch_build_barricade_50_desc",
        category = "nailed_it",
        stat = "barricades_built",
        target = 50,
        tier = "silver",
    },
    {
        id = "build_wall_25",
        name = "UI_LugliAch_build_wall_25_name",
        description = "UI_LugliAch_build_wall_25_desc",
        category = "nailed_it",
        stat = "walls_built",
        target = 25,
        tier = "silver",
    },
    {
        id = "build_gen_1",
        name = "UI_LugliAch_build_gen_1_name",
        description = "UI_LugliAch_build_gen_1_desc",
        category = "nailed_it",
        stat = "generators_started",
        target = 1,
        tier = "bronze",
    },
    {
        id = "build_gen_5",
        name = "UI_LugliAch_build_gen_5_name",
        description = "UI_LugliAch_build_gen_5_desc",
        category = "nailed_it",
        stat = "generators_started",
        target = 5,
        tier = "silver",
    },
    {
        id = "build_safehouse_1",
        name = "UI_LugliAch_build_safehouse_1_name",
        description = "UI_LugliAch_build_safehouse_1_desc",
        category = "nailed_it",
        stat = "safehouse_claimed",
        target = 1,
        tier = "bronze",
    },
    {
        id = "build_craft_100",
        name = "UI_LugliAch_build_craft_100_name",
        description = "UI_LugliAch_build_craft_100_desc",
        category = "nailed_it",
        stat = "items_crafted",
        target = 100,
        unit = "UI_LugliAch_unit_items",
        tier = "silver",
    },
    {
        id = "build_craft_1000",
        name = "UI_LugliAch_build_craft_1000_name",
        description = "UI_LugliAch_build_craft_1000_desc",
        category = "nailed_it",
        stat = "items_crafted",
        target = 1000,
        unit = "UI_LugliAch_unit_items",
        tier = "gold",
    },
    {
        id = "build_rooms_10",
        name = "UI_LugliAch_build_rooms_10_name",
        description = "UI_LugliAch_build_rooms_10_desc",
        category = "nailed_it",
        stat = "rooms_built_in",
        target = 10,
        tier = "silver",
    },
    {
        id = "build_dismantle_100",
        name = "UI_LugliAch_build_dismantle_100_name",
        description = "UI_LugliAch_build_dismantle_100_desc",
        category = "nailed_it",
        stat = "things_dismantled",
        target = 100,
        tier = "silver",
    },
    {
        id = "build_padlock_10",
        name = "UI_LugliAch_build_padlock_10_name",
        description = "UI_LugliAch_build_padlock_10_desc",
        category = "nailed_it",
        stat = "padlocks_fitted",
        target = 10,
        tier = "silver",
    },
    {
        id = "build_stairs_1",
        name = "UI_LugliAch_build_stairs_1_name",
        description = "UI_LugliAch_build_stairs_1_desc",
        category = "nailed_it",
        stat = "stairs_dug",
        target = 1,
        tier = "bronze",
    },
    {
        id = "build_plumb_5",
        name = "UI_LugliAch_build_plumb_5_name",
        description = "UI_LugliAch_build_plumb_5_desc",
        category = "nailed_it",
        stat = "things_plumbed",
        target = 5,
        tier = "silver",
    },
}

for i = 1, #DEFS do
    M.register(DEFS[i])
end

M.status("Nailed It definitions", true)
