require "LugliAchievements/Categories"

local M = LugliAchievements

local DEFS = {
    {
        id = "road_drive_100",
        name = "UI_LugliAch_road_drive_100_name",
        description = "UI_LugliAch_road_drive_100_desc",
        category = "roadside",
        stat = "metres_driven",
        target = 100000,
        unit = "UI_LugliAch_unit_metres",
        tier = "bronze",
    },
    {
        id = "road_drive_1000",
        name = "UI_LugliAch_road_drive_1000_name",
        description = "UI_LugliAch_road_drive_1000_desc",
        category = "roadside",
        stat = "metres_driven",
        target = 1000000,
        unit = "UI_LugliAch_unit_metres",
        tier = "gold",
    },
    {
        id = "road_vehicles_10",
        name = "UI_LugliAch_road_vehicles_10_name",
        description = "UI_LugliAch_road_vehicles_10_desc",
        category = "roadside",
        stat = "vehicles_used",
        target = 10,
        tier = "silver",
    },
    {
        id = "road_enters_100",
        name = "UI_LugliAch_road_enters_100_name",
        description = "UI_LugliAch_road_enters_100_desc",
        category = "roadside",
        stat = "vehicle_enters",
        target = 100,
        tier = "silver",
    },
    {
        id = "road_seat_10",
        name = "UI_LugliAch_road_seat_10_name",
        description = "UI_LugliAch_road_seat_10_desc",
        category = "roadside",
        stat = "seat_changes",
        target = 10,
        tier = "silver",
    },
    {
        id = "road_repair_1",
        name = "UI_LugliAch_road_repair_1_name",
        description = "UI_LugliAch_road_repair_1_desc",
        category = "roadside",
        stat = "vehicle_repairs",
        target = 1,
        tier = "bronze",
    },
    {
        id = "road_repair_25",
        name = "UI_LugliAch_road_repair_25_name",
        description = "UI_LugliAch_road_repair_25_desc",
        category = "roadside",
        stat = "vehicle_repairs",
        target = 25,
        tier = "silver",
    },
    {
        id = "road_fuel_100",
        name = "UI_LugliAch_road_fuel_100_name",
        description = "UI_LugliAch_road_fuel_100_desc",
        category = "roadside",
        stat = "refuels",
        target = 100,
        tier = "silver",
    },
    {
        id = "road_battery_10",
        name = "UI_LugliAch_road_battery_10_name",
        description = "UI_LugliAch_road_battery_10_desc",
        category = "roadside",
        stat = "batteries_charged",
        target = 10,
        tier = "silver",
    },
    {
        id = "road_fumes_1",
        name = "UI_LugliAch_road_fumes_1_name",
        description = "UI_LugliAch_road_fumes_1_desc",
        category = "roadside",
        stat = "low_fuel_drives",
        target = 1,
        tier = "bronze",
    },
    {
        id = "see_louisville_1",
        name = "UI_LugliAch_see_louisville_1_name",
        description = "UI_LugliAch_see_louisville_1_desc",
        category = "roadside",
        stat = "saw_louisville",
        target = 1,
        tier = "bronze",
    },
    {
        id = "see_regions_9",
        name = "UI_LugliAch_see_regions_9_name",
        description = "UI_LugliAch_see_regions_9_desc",
        category = "roadside",
        stat = "regions_seen",
        target = 9,
        tier = "silver",
    },
    {
        id = "see_airport_1",
        name = "UI_LugliAch_see_airport_1_name",
        description = "UI_LugliAch_see_airport_1_desc",
        category = "roadside",
        stat = "saw_airport",
        target = 1,
        tier = "bronze",
    },
    {
        id = "see_rooms_100",
        name = "UI_LugliAch_see_rooms_100_name",
        description = "UI_LugliAch_see_rooms_100_desc",
        category = "roadside",
        stat = "rooms_seen",
        target = 100,
        tier = "bronze",
    },
    {
        id = "see_rooms_1000",
        name = "UI_LugliAch_see_rooms_1000_name",
        description = "UI_LugliAch_see_rooms_1000_desc",
        category = "roadside",
        stat = "rooms_seen",
        target = 1000,
        tier = "gold",
    },
    {
        id = "see_roomkinds_50",
        name = "UI_LugliAch_see_roomkinds_50_name",
        description = "UI_LugliAch_see_roomkinds_50_desc",
        category = "roadside",
        stat = "room_kinds",
        target = 50,
        tier = "silver",
    },
    {
        id = "see_buildings_10",
        name = "UI_LugliAch_see_buildings_10_name",
        description = "UI_LugliAch_see_buildings_10_desc",
        category = "roadside",
        stat = "buildings_explored",
        target = 10,
        tier = "bronze",
    },
    {
        id = "see_buildings_50",
        name = "UI_LugliAch_see_buildings_50_name",
        description = "UI_LugliAch_see_buildings_50_desc",
        category = "roadside",
        stat = "buildings_explored",
        target = 50,
        tier = "gold",
    },
    {
        id = "see_shops_25",
        name = "UI_LugliAch_see_shops_25_name",
        description = "UI_LugliAch_see_shops_25_desc",
        category = "roadside",
        stat = "shops_seen",
        target = 25,
        tier = "silver",
    },
    {
        id = "see_bathroom_100",
        name = "UI_LugliAch_see_bathroom_100_name",
        description = "UI_LugliAch_see_bathroom_100_desc",
        category = "roadside",
        stat = "bathrooms_seen",
        target = 100,
        tier = "silver",
    },
    {
        id = "see_church_10",
        name = "UI_LugliAch_see_church_10_name",
        description = "UI_LugliAch_see_church_10_desc",
        category = "roadside",
        stat = "churches_seen",
        target = 10,
        tier = "silver",
    },
    {
        id = "see_prison_1",
        name = "UI_LugliAch_see_prison_1_name",
        description = "UI_LugliAch_see_prison_1_desc",
        category = "roadside",
        stat = "saw_prison",
        target = 1,
        tier = "bronze",
    },
    {
        id = "see_spiffo_1",
        name = "UI_LugliAch_see_spiffo_1_name",
        description = "UI_LugliAch_see_spiffo_1_desc",
        category = "roadside",
        stat = "saw_spiffo",
        target = 1,
        tier = "bronze",
    },
    {
        id = "see_bigspiffo_1",
        name = "UI_LugliAch_see_bigspiffo_1_name",
        description = "UI_LugliAch_see_bigspiffo_1_desc",
        category = "roadside",
        stat = "saw_bigspiffo",
        target = 1,
        tier = "bronze",
    },
    {
        id = "see_toys_10",
        name = "UI_LugliAch_see_toys_10_name",
        description = "UI_LugliAch_see_toys_10_desc",
        category = "roadside",
        stat = "toys_found",
        target = 10,
        unit = "UI_LugliAch_unit_toys",
        tier = "silver",
    },
    {
        id = "see_toys_26",
        name = "UI_LugliAch_see_toys_26_name",
        description = "UI_LugliAch_see_toys_26_desc",
        category = "roadside",
        stat = "toys_found",
        target = 26,
        unit = "UI_LugliAch_unit_toys",
        tier = "gold",
    },
    {
        id = "road_walk_10",
        name = "UI_LugliAch_road_walk_10_name",
        description = "UI_LugliAch_road_walk_10_desc",
        category = "roadside",
        stat = "metres_walked",
        target = 10000,
        unit = "UI_LugliAch_unit_metres",
        tier = "bronze",
    },
    {
        id = "road_walk_100",
        name = "UI_LugliAch_road_walk_100_name",
        description = "UI_LugliAch_road_walk_100_desc",
        category = "roadside",
        stat = "metres_walked",
        target = 100000,
        unit = "UI_LugliAch_unit_metres",
        tier = "gold",
    },
}

for i = 1, #DEFS do
    M.register(DEFS[i])
end

M.status("Roadside Attractions definitions", true)
