require "LugliAchievements/Categories"

local M = LugliAchievements

local DEFS = {
    {
        id = "secret_lifeandliving",
        name = "UI_LugliAch_secret_lifeandliving_name",
        description = "UI_LugliAch_secret_lifeandliving_desc",
        category = "secrets",
        stat = "ll_days",
        target = 12,
        unit = "UI_LugliAch_unit_days",
        hidden = true,
        hiddenText = "UI_LugliAch_secret_lifeandliving_hidden",
        tier = "gold",
    },
    {
        id = "secret_tv_10",
        name = "UI_LugliAch_secret_tv_10_name",
        description = "UI_LugliAch_secret_tv_10_desc",
        category = "secrets",
        stat = "tv_channels",
        target = 10,
        hidden = true,
        hiddenText = "UI_LugliAch_secret_tv_10_hidden",
        tier = "silver",
    },
    {
        id = "secret_radio_5",
        name = "UI_LugliAch_secret_radio_5_name",
        description = "UI_LugliAch_secret_radio_5_desc",
        category = "secrets",
        stat = "radio_stations",
        target = 5,
        hidden = true,
        hiddenText = "UI_LugliAch_secret_radio_5_hidden",
        tier = "silver",
    },
    {
        id = "secret_military_1",
        name = "UI_LugliAch_secret_military_1_name",
        description = "UI_LugliAch_secret_military_1_desc",
        category = "secrets",
        stat = "saw_military_freq",
        target = 1,
        hidden = true,
        hiddenText = "UI_LugliAch_secret_military_1_hidden",
        tier = "bronze",
    },
    {
        id = "secret_offgrid",
        name = "UI_LugliAch_secret_offgrid_name",
        description = "UI_LugliAch_secret_offgrid_desc",
        category = "secrets",
        stat = "off_grid_days",
        target = 30,
        unit = "UI_LugliAch_unit_days",
        hidden = true,
        hiddenText = "UI_LugliAch_secret_offgrid_hidden",
        tier = "gold",
    },
    {
        id = "secret_nowater",
        name = "UI_LugliAch_secret_nowater_name",
        description = "UI_LugliAch_secret_nowater_desc",
        category = "secrets",
        stat = "no_water_days",
        target = 30,
        unit = "UI_LugliAch_unit_days",
        hidden = true,
        hiddenText = "UI_LugliAch_secret_nowater_hidden",
        tier = "gold",
    },
    {
        id = "secret_sprinter",
        name = "UI_LugliAch_secret_sprinter_name",
        description = "UI_LugliAch_secret_sprinter_desc",
        category = "secrets",
        stat = "killed_sprinter",
        target = 1,
        hidden = true,
        hiddenText = "UI_LugliAch_secret_sprinter_hidden",
        tier = "bronze",
    },
    {
        id = "secret_fakedead",
        name = "UI_LugliAch_secret_fakedead_name",
        description = "UI_LugliAch_secret_fakedead_desc",
        category = "secrets",
        stat = "killed_fakedead",
        target = 1,
        hidden = true,
        hiddenText = "UI_LugliAch_secret_fakedead_hidden",
        tier = "bronze",
    },
    {
        id = "secret_naked_50",
        name = "UI_LugliAch_secret_naked_50_name",
        description = "UI_LugliAch_secret_naked_50_desc",
        category = "secrets",
        stat = "kills_naked",
        target = 50,
        unit = "UI_LugliAch_unit_zombies",
        hidden = true,
        hiddenText = "UI_LugliAch_secret_naked_50_hidden",
        tier = "silver",
    },
    {
        id = "secret_blizzard_out",
        name = "UI_LugliAch_secret_blizzard_out_name",
        description = "UI_LugliAch_secret_blizzard_out_desc",
        category = "secrets",
        stat = "blizzard_outdoors",
        target = 1,
        hidden = true,
        hiddenText = "UI_LugliAch_secret_blizzard_out_hidden",
        tier = "bronze",
    },
    {
        id = "secret_pacifist_30",
        name = "UI_LugliAch_secret_pacifist_30_name",
        description = "UI_LugliAch_secret_pacifist_30_desc",
        category = "secrets",
        stat = "pacifist_days",
        target = 30,
        unit = "UI_LugliAch_unit_days",
        hidden = true,
        hiddenText = "UI_LugliAch_secret_pacifist_30_hidden",
        tier = "silver",
    },
    {
        id = "secret_basement_1",
        name = "UI_LugliAch_secret_basement_1_name",
        description = "UI_LugliAch_secret_basement_1_desc",
        category = "secrets",
        stat = "saw_basement",
        target = 1,
        hidden = true,
        hiddenText = "UI_LugliAch_secret_basement_1_hidden",
        tier = "bronze",
    },
    {
        id = "secret_startled_1",
        name = "UI_LugliAch_secret_startled_1_name",
        description = "UI_LugliAch_secret_startled_1_desc",
        category = "secrets",
        stat = "startled",
        target = 1,
        tier = "bronze",
        hidden = true,
        hiddenText = "UI_LugliAch_secret_startled_1_hidden",
    },
    {
        id = "secret_wizard_1",
        name = "UI_LugliAch_secret_wizard_1_name",
        description = "UI_LugliAch_secret_wizard_1_desc",
        category = "secrets",
        stat = "wore_wizard_hat",
        target = 1,
        tier = "bronze",
        hidden = true,
        hiddenText = "UI_LugliAch_secret_wizard_1_hidden",
    },
    {
        id = "secret_smoke_10",
        name = "UI_LugliAch_secret_smoke_10_name",
        description = "UI_LugliAch_secret_smoke_10_desc",
        category = "secrets",
        stat = "smokes_nonsmoker",
        target = 10,
        tier = "silver",
        hidden = true,
        hiddenText = "UI_LugliAch_secret_smoke_10_hidden",
    },
    -- The one row in this category that is not hidden: its name gives nothing away, and hiding
    -- it would need a hiddenText string in every shipped language.
    {
        id = "combat_nogun_500",
        name = "UI_LugliAch_combat_nogun_500_name",
        description = "UI_LugliAch_combat_nogun_500_desc",
        category = "secrets",
        stat = "kills_quiet",
        target = 500,
        unit = "UI_LugliAch_unit_zombies",
        tier = "silver",
    },
}

for i = 1, #DEFS do
    M.register(DEFS[i])
end

M.status("Secrets definitions", true)
