require "LugliAchievements/Categories"

local M = LugliAchievements

local DEFS = {
    {
        id = "survive_days_7",
        name = "UI_LugliAch_survive_days_7_name",
        description = "UI_LugliAch_survive_days_7_desc",
        category = "still_breathing",
        stat = "days_survived",
        target = 7,
        unit = "UI_LugliAch_unit_days",
        tier = "silver",
    },
    {
        id = "survive_days_28",
        name = "UI_LugliAch_survive_days_28_name",
        description = "UI_LugliAch_survive_days_28_desc",
        category = "still_breathing",
        stat = "days_survived",
        target = 28,
        unit = "UI_LugliAch_unit_days",
        tier = "silver",
    },
    {
        id = "survive_days_90",
        name = "UI_LugliAch_survive_days_90_name",
        description = "UI_LugliAch_survive_days_90_desc",
        category = "still_breathing",
        stat = "days_survived",
        target = 90,
        unit = "UI_LugliAch_unit_days",
        tier = "silver",
    },
    {
        id = "survive_days_180",
        name = "UI_LugliAch_survive_days_180_name",
        description = "UI_LugliAch_survive_days_180_desc",
        category = "still_breathing",
        stat = "days_survived",
        target = 180,
        unit = "UI_LugliAch_unit_days",
        tier = "silver",
    },
    {
        id = "survive_days_365",
        name = "UI_LugliAch_survive_days_365_name",
        description = "UI_LugliAch_survive_days_365_desc",
        category = "still_breathing",
        stat = "days_survived",
        target = 365,
        unit = "UI_LugliAch_unit_days",
        tier = "gold",
    },
    {
        id = "survive_days_730",
        name = "UI_LugliAch_survive_days_730_name",
        description = "UI_LugliAch_survive_days_730_desc",
        category = "still_breathing",
        stat = "days_survived",
        target = 730,
        unit = "UI_LugliAch_unit_days",
        tier = "gold",
    },
    {
        id = "survive_heli_1",
        name = "UI_LugliAch_survive_heli_1_name",
        description = "UI_LugliAch_survive_heli_1_desc",
        category = "still_breathing",
        stat = "helicopter_survived",
        target = 1,
        tier = "bronze",
    },
    {
        id = "survive_winter_1",
        name = "UI_LugliAch_survive_winter_1_name",
        description = "UI_LugliAch_survive_winter_1_desc",
        category = "still_breathing",
        stat = "saw_winter",
        target = 1,
        tier = "bronze",
    },
    {
        id = "survive_seasons_4",
        name = "UI_LugliAch_survive_seasons_4_name",
        description = "UI_LugliAch_survive_seasons_4_desc",
        category = "still_breathing",
        stat = "seasons_seen",
        target = 4,
        tier = "silver",
    },
    {
        id = "survive_blizzard_1",
        name = "UI_LugliAch_survive_blizzard_1_name",
        description = "UI_LugliAch_survive_blizzard_1_desc",
        category = "still_breathing",
        stat = "blizzards",
        target = 1,
        tier = "bronze",
    },
    {
        id = "survive_tropical_1",
        name = "UI_LugliAch_survive_tropical_1_name",
        description = "UI_LugliAch_survive_tropical_1_desc",
        category = "still_breathing",
        stat = "storms",
        target = 1,
        tier = "bronze",
    },
    {
        id = "survive_thunder_50",
        name = "UI_LugliAch_survive_thunder_50_name",
        description = "UI_LugliAch_survive_thunder_50_desc",
        category = "still_breathing",
        stat = "thunder_heard",
        target = 50,
        tier = "silver",
    },
    {
        id = "survive_nodamage_7",
        name = "UI_LugliAch_survive_nodamage_7_name",
        description = "UI_LugliAch_survive_nodamage_7_desc",
        category = "still_breathing",
        stat = "clean_days_best",
        target = 7,
        unit = "UI_LugliAch_unit_days",
        tier = "silver",
    },
    {
        id = "survive_moodles_8",
        name = "UI_LugliAch_survive_moodles_8_name",
        description = "UI_LugliAch_survive_moodles_8_desc",
        category = "still_breathing",
        stat = "moodles_worst",
        target = 8,
        tier = "silver",
    },
    {
        id = "survive_sleep_50",
        name = "UI_LugliAch_survive_sleep_50_name",
        description = "UI_LugliAch_survive_sleep_50_desc",
        category = "still_breathing",
        stat = "sleeps",
        target = 50,
        tier = "silver",
    },
    {
        id = "survive_rest_100",
        name = "UI_LugliAch_survive_rest_100_name",
        description = "UI_LugliAch_survive_rest_100_desc",
        category = "still_breathing",
        stat = "rests",
        target = 100,
        tier = "silver",
    },
    {
        id = "survive_water_500",
        name = "UI_LugliAch_survive_water_500_name",
        description = "UI_LugliAch_survive_water_500_desc",
        category = "still_breathing",
        stat = "drinks",
        target = 500,
        tier = "silver",
    },
    {
        id = "survive_noxious_1",
        name = "UI_LugliAch_survive_noxious_1_name",
        description = "UI_LugliAch_survive_noxious_1_desc",
        category = "still_breathing",
        stat = "noxious",
        target = 1,
        tier = "bronze",
    },
    {
        id = "survive_awake_72",
        name = "UI_LugliAch_survive_awake_72_name",
        description = "UI_LugliAch_survive_awake_72_desc",
        category = "still_breathing",
        stat = "awake_hours_best",
        target = 72,
        tier = "silver",
    },
}

for i = 1, #DEFS do
    M.register(DEFS[i])
end

M.status("Still Breathing definitions", true)
